services:
  backend:
    build:
        context: ./backend
  frontend:
    build:
        context: ./frontend
    ports:
      - "8080:5000"
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
 # rabbitmq:
 #   image: "rabbitmq:alpine"
