version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    replicas: 0
  frontend:
    build:
      context: ./sportwetten_frontend
    environment:
      NODE_ENV: production
    ports:
      - "8000:3000" # Mapping port 3000 of container to 8000 on host

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes: 
      - ./redis_data:/data:z
  # rabbitmq:
  #   image: "rabbitmq:alpine"
  #   ports:
  #     - "5672:5672"
